# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db92003594ac695b091e555acb8e5ae454d877ddd80f393fe2aa973343f1efb4cfa99702c01fb5803e3c57124e5293b846a40d2a7d194b007bc7701f303e3d0d

test:
  secret_key_base: ab43e61e8d7b963541a165ce455e3f9708e6b06c0cea149f4eea53766e5c4547f8f8662c1f5391626f56382d571dbd65b5b0b30852d08ec8da74fa75e58ef102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
